#!/bin/bash
# build frontend
./scripts/build_frontend.sh

# build gradio wheel
python3 -m build -w -o ./dist

# build gradio_client wheel
cd client/python
python3 -m build -w -o ./../../dist

# upload wheels to pypi
cd ../../
twine upload --non-interactive --repository-url https://pypi.fitsonchips.com/ -u fitsonchips -p foc-pypi-dev ./dist/*